# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: heart-service
  labels:
    app: heart-model
spec:
  selector:
    app: heart-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer